site_name: WSo2 API Manager 2.6.0
site_description: WSO2 API Manager
site_author: WSO2
site_url: https://wso2.github.io/apim2.6
repo_name: Siddhi
repo_url: https://github.com/shaniR/product-apim/tree/product-scenarios
edit_url: product-scenarios
theme: 'default'
pages:
- Welcome to APIM: 'README.md'
