site_name: WSo2 API Manager 2.6.0
site_description: WSO2 API Manager
site_author: WSO2
site_url: https://wso2.github.io/apim2.6
extra_css:
- stylesheets/extra.css
repo_name: prodct-apim
repo_url: https://github.com/shaniR/product-apim/tree/product-scenarios/
edit_url: product-scenarios
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  palette:
    primary: teal
    accent: teal
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome to APIM: README.md
